# ======================
# POSTGRESQL – WORKERS
# PG 17 + Citus 13.2.0
# ======================

# --- REQUERIDO PARA CITUS ---
shared_preload_libraries = 'citus'
listen_addresses = '*'

# ----- MEMORIA -----
shared_buffers = 384MB
work_mem = 8MB
maintenance_work_mem = 64MB

# ----- CONEXIONES -----
max_connections = 200

# ----- REQUERIDO/RECOMENDADO PARA CITUS (evita override logs) -----
max_prepared_transactions = 200

# ----- PARALELISMO -----
max_parallel_workers = 2
max_parallel_workers_per_gather = 1