# =========================
# POSTGRESQL â€“ COORDINATOR
# PG 17 + Citus 13.2.0
# =========================

# --- REQUIRED FOR CITUS ---
shared_preload_libraries = 'citus'

# (Opcional) Ãºtil para containers
listen_addresses = '*'

# ----- MEMORIA -----
shared_buffers = 512MB
work_mem = 16MB
maintenance_work_mem = 128MB

# ----- CONEXIONES -----
max_connections = 200

# ----- REQUERIDO/RECOMENDADO PARA CITUS (evita override logs) -----
max_prepared_transactions = 200

# ----- PARALELISMO -----
max_parallel_workers = 2
max_parallel_workers_per_gather = 1

# ----- CITUS -----
citus.enable_repartition_joins = on

# Valores vÃ¡lidos: never | always
# (Para mi tesis y consistencia: no usarÃ© nodos secundarios)
citus.use_secondary_nodes = never
